service: nestjs-netlify

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /{proxy+}
          method: any
    environment:
      NODE_ENV: production

plugins:
  - serverless-webpack
  - serverless-offline
