ALTER TABLE "bot" ADD COLUMN IF NOT EXISTS "parent_name" VARCHAR(255);
ALTER TABLE "bot" ADD COLUMN IF NOT EXISTS "parent_surname" VARCHAR(255);
ALTER TABLE "bot" ADD COLUMN IF NOT EXISTS "student_name" VARCHAR(255);
ALTER TABLE "bot" ADD COLUMN IF NOT EXISTS "student_surname" VARCHAR(255);
